title: "Minseo’s Dev Blog"
description: "ML & MLSys blog and notes"
url: "https://minseoc03.github.io"
baseurl: ""   # 레포가 user.github.io면 빈 문자열

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /:categories/:title/

# Plugins (GitHub Pages 허용 목록)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Collections
collections:
  ml:
    output: true
    permalink: /ml/:path/
  mlsys:
    output: true
    permalink: /mlsys/:path/
  about:
    output: true
    permalink: /about/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      mathjax: true
      show_excerpts: false
  - scope:
      path: ""
      type: ml
    values:
      layout: single
      sidebar: ml
      author_profile: true
  - scope:
      path: ""
      type: mlsys
    values:
      layout: single
      sidebar: mlsys
      author_profile: true
  - scope:
      path: ""
      type: about
    values:
      layout: single
      sidebar: about
      author_profile: true

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Minimal Mistakes options
minimal_mistakes_skin: "default"
search: true

include: ["_pages"]
show_date: true
date_format: "%b %d, %Y"

sass:
  sass_dir: _sass


# Author (optional)
author:
  name: "Minseo Choi"
  avatar: "/assets/images/profile.png"
  bio: "Sophomore @ JHU<br>Passionate about ML & MLSys"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/minseoc03"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/minseoc03/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:cfi3288@gmail.com"
