title: "Minseo’s Notes"
description: "ML & MLSys blog and notes"
url: "https://minseoc03.github.io"
baseurl: ""   # 레포가 user.github.io면 빈 문자열

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Plugins (GitHub Pages 허용 목록)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Collections
collections:
  ml:
    output: true
    permalink: /ml/:path/
  mlsys:
    output: true
    permalink: /mlsys/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: ml
    values:
      layout: single
      sidebar: ml
      author_profile: true
  - scope:
      path: ""
      type: mlsys
    values:
      layout: single
      sidebar: mlsys
      author_profile: true

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Minimal Mistakes options
minimal_mistakes_skin: "default"
search: true

# Author (optional)
author:
  name: "Minseo Choi"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/minseoc03"
