# Site basics
locale: "en-US"
title: "Minseo’s Dev Blog"
description: "ML & MLSys blog and notes"
url: "https://minseoc03.github.io"
baseurl: "" # if using <user>.github.io; otherwise set to "/repo-name"


# Theme (remote if using GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes"


# Plugins
plugins:
- jekyll-include-cache
- jekyll-feed
- jekyll-seo-tag


# Collections for sections
collections:
ml:
output: true
permalink: /ml/:path/
mlsys:
output: true
permalink: /mlsys/:path/


# Defaults for content types
defaults:
# Blog posts
- scope:
path: ""
type: posts
values:
layout: single
author_profile: true


# ML docs
- scope:
path: "_ml"
type: ml
values:
layout: single
sidebar: ml
author_profile: true


# MLSys docs
- scope:
path: "_mlsys"
type: mlsys
values:
layout: single
sidebar: mlsys
author_profile: true


# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"


# Minimal Mistakes settings
minimal_mistakes_skin: "default" # "air", "contrast", etc.
search: true


# Build
markdown: kramdown
highlighter: rouge


# Social (optional)
author:
name: "Minseo Choi"
links:
- label: "GitHub"
icon: "fab fa-github"
url: "https://github.com/minseoc03"